### PR TITLE
fixed responsiveness issues

### LINKED ISSUE #2: Weekend Frontend ₦10k Challenge: Make this Responsive
# Problem

This design looks great on desktop screens. However, on smaller screens (see screenshots below), the layout is broken. 

## Challenge

Fix the layout for the following screens:

- iPad
- iPhone 6/7/8 Plus or Galaxy S5

while keeping the desktop view on point.

## For Contestants

- Fork this repository
- Assign this issue to yourself or Comment, so I know you are working on it.
- Create a PR early, even if it is a draft, so I can follow your progress.
- Ask questions on this thread, [or reach out on twitter](https://twitter.com/mykeels).
- Show design concept before writing code with screenshots in the PR.
- Provide screenshots of the final results for the different screens, exactly like I have done below in your PR.
- Complete this by 11:59pm on Sunday, 24th May, 2020.
- The person behind the first merged PR gets ₦10,000 from me.

## Additional Context

The app is built with Angular JS, so it might appear a daunting task. These two files can serve as your starting point.

- [index.html](https://github.com/mykeels/tic-tac-toe/blob/master/src/index.html)
- [style.css](https://github.com/mykeels/tic-tac-toe/blob/master/src/css/style.css)

The tic-tac-toe board scales up from 3x3 to 10x10, so make sure they all display well in your design. Your screenshots should show 10x10 though (feel free to add others).

Feel free to upgrade the bootstrap, switch to tailwind, or go wild by using hand-crafted CSS.

Make us proud ❤️

## Screenshots

- Desktop

image

- iPad (current)

image

- iPhone 6/7/8 Plus (current)

image

### PR DESCRIPTION
**Pull request by Chimdiya1**
Resolves #2

**Galaxy s5**
s5 3x3
s5 6x6
s5 10x10

**Iphone6/7/8 plus**
iphone 3x3
iphone 6x6
iphone10x10

**ipad**
ipad 3x3
ipad 6x6
ipad10x10

### CODE REVIEW

**Comment by mykeels** [comment]
This is amazing work.

I can't help but think that the final screenshot for the iPad can have larger tiles.

**Comment by mykeels** [comment]
Add a `min-height: 100vh; background-size: cover` to the `body`, and I'll merge this.

Thanks, I love this! ❤

Congratulations! 🙌

**Comment by Chimdiya1** [comment]
I will add it ASAP, thanks!!!

**Comment by Chimdiya1** [comment]
@mykeels Done :grin:

**Pull request merged**
